"""
DOCX export for STR drafts.

Uses stock `python-docx` — the mainline library has no native Word-footnote
support (a long-standing, still-unresolved upstream limitation: see
python-openxml/python-docx#1, open since 2014). Forks that add it
(bayoo-docx, python-docx-ng) are small, less-maintained side projects, and
hand-rolling real footnotes means patching raw OOXML (word/footnotes.xml,
relationships, content types) — more fragile than the value it adds here.

Citations are rendered instead as numbered inline markers (superscript
`[1]`, `[2]`, ...) resolving to a "Sources" list at the end of the document —
the same practical citation contract as a footnote (jump from a claim to its
exact source), without an extra dependency or hand-rolled XML. If real
in-document footnotes are wanted later, this is the one place that would
need to change.
"""

from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH


def str_docx_filename(case_id: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    safe_case_id = "".join(c for c in case_id if c.isalnum() or c in ("-", "_")) or "CASE"
    return f"STR_{safe_case_id}_{timestamp}.docx"


def build_str_docx(draft: dict[str, Any]) -> bytes:
    """Renders a `build_str_draft()` result into a .docx file, returned as raw bytes."""
    data = draft["exportable_data"]
    doc = Document()

    doc.add_heading("Suspicious Transaction Report — Draft", level=1)
    doc.add_paragraph(
        "Draft for analyst review only. Not a filing. Not submitted to FIU-IND. Not legal advice."
    ).runs[0].italic = True

    doc.add_heading("Case Summary", level=2)
    doc.add_paragraph(f"Case ID: {data['case_id']}")
    doc.add_paragraph(f"Tier: {data['tier_origin']}")
    doc.add_paragraph(f"Primary transaction: {data['primary_transaction_id']}")
    doc.add_paragraph(f"Account(s): {', '.join(data['account_ids']) or 'Not available'}")
    doc.add_paragraph(
        f"Date range: {data['date_range']['start'] or 'N/A'} to {data['date_range']['end'] or 'N/A'}"
    )
    doc.add_paragraph(f"Amount(s) cited in evidence: {', '.join(data['amounts_cited']) or 'Not available'}")
    risk_score = data.get("risk_score")
    doc.add_paragraph(f"Risk score: {risk_score:.2f}" if isinstance(risk_score, (int, float)) else "Risk score: N/A")
    doc.add_paragraph(f"Generated: {data['generated_at']}")

    doc.add_heading("Reasons for Suspicion (suggested — analyst must confirm)", level=2)
    if data["reasons_for_suspicion"]:
        for reason in data["reasons_for_suspicion"]:
            doc.add_paragraph(f"[{reason['code']}] {reason['label']} — {reason['basis']}", style="List Bullet")
    else:
        doc.add_paragraph("No category could be suggested from the available evidence.")

    doc.add_heading("Grounds of Suspicion — Narrative", level=2)
    sentences = draft["sentences_with_citations"]
    if sentences:
        for idx, item in enumerate(sentences, start=1):
            paragraph = doc.add_paragraph()
            paragraph.add_run(f"{item['sentence']} ")
            marker = paragraph.add_run(f"[{idx}]")
            marker.font.superscript = True
    else:
        doc.add_paragraph("No sentences passed independent grounding verification for this case.")

    doc.add_heading("Sources", level=2)
    if sentences:
        for idx, item in enumerate(sentences, start=1):
            doc.add_paragraph(
                f"[{idx}] Event {item['event_id'] or 'unknown'} "
                f"({item['tool_called'] or 'unknown tool'}) at {item['timestamp'] or 'unknown time'}"
            )
    else:
        doc.add_paragraph("No cited sources.")

    doc.add_heading("Review Notes (Failed Validator Checks)", level=2)
    if draft["validator_notes"]:
        for note in draft["validator_notes"]:
            doc.add_paragraph(f'REJECTED: "{note["sentence"]}" — {note["reason"]}', style="List Bullet")
    else:
        doc.add_paragraph("No sentences were rejected by the independent grounding validator.")

    doc.add_heading("Sections Not Populated", level=2)
    for gap in data["missing_sections"]:
        doc.add_paragraph(gap, style="List Bullet")

    footer = doc.sections[0].footer
    footer_paragraph = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    footer_paragraph.text = "Draft for analyst review. Generated by Verity. Not automatically filed."
    footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
